# Generated by Django 4.2.4 on 2023-09-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
